- hosts: all
  become: yes

  tasks:
    - name: install packages
      apt:
        name: ['python3-pip']
        update_cache: yes

    - name: install python modules
      pip:
        name: ['docker']

    - name: Deploy app
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: app
        image: redmine
        ports:
          - "5000:3000"
        env:
          REDMINE_DB_POSTGRES: '{{ REDMINE_DB_POSTGRES }}'
          REDMINE_DB_PORT: '{{ REDMINE_DB_PORT }}'
          REDMINE_DB_USERNAME: '{{ REDMINE_DB_USERNAME }}'
          REDMINE_DB_PASSWORD: '{{ REDMINE_DB_PASSWORD }}'
          REDMINE_DB_DATABASE: '{{ REDMINE_DB_DATABASE }}'

- hosts: webservers
  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "datadoghq.eu"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Application health check status
            url: http://localhost:5000
            timeout: 5
            method: GET
  tasks:
    - name: install and run Datadog agent
      include_role:
        name: datadog.datadog

