- import_playbook: app.yml

- hosts: webservers
  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "datadoghq.eu"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Application health check status
            url: http://localhost:5000
            timeout: 5
            method: GET
  tasks:
    - name: install and run Datadog agent
      include_role:
        name: datadog.datadog

