- hosts: all
  become: yes
  tags: preparing
  pre_tasks:
    - name: apt update cache and upgrade
      apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600

  roles:
    - geerlingguy.pip
